### ISSUE TITLE
add a reference to the article

### ISSUE THREAD

**Issue by paolodina** [Jordanirabor/django_social_app#1]
https://scotch.io/tutorials/django-authentication-with-facebook-instagram-and-linkedin

**Comment by Jordanirabor** [comment]
Why should I reference a plagiarized version of my work? I'm Jordan and the article in that link is a repost without credit of any sort.

**Comment by paolodina** [comment]
I'm really sorry @Jordanirabor totally my fault. I found this repo because I read that article without realizing it was an unauthorized copy... I will edit the issue referencing your original article, I still believe it worth to add a reference to the original one, at least to avoid such kind of situation.

Thank you very much for your work.
